services:
  - type: web
    name: your-portfolio-backend
    env: php
    buildCommand: "./scripts/build.sh"
    startCommand: "php artisan serve --host=0.0.0.0 --port=$PORT"
    envVars:
      - key: APP_KEY
        generateValue: true
      - key: NODE_VERSION
        value: "20"
      - key: PHP_VERSION
        value: "8.2"
